### ISSUE TITLE
多线程对同一个socket进行accept

### ISSUE THREAD

**Issue by lingchenye** [Buerzhu/TinyWeb#1]
有一个问题，处理新连接的逻辑为什么不放在主线程中呢？在现有的逻辑中处理新连接的逻辑放在了子线程中，但是也没有加锁，这样有可能出现多个线程同时对同一个socket进行accept操作的场景，这种情况下，程序的行为是未定义的，而且即使加锁也会由性能问题吧。

**Comment by Buerzhu** [comment]
listenfd是工作在oneshot模式下的，所以不会出现多个工作线程同时对同一个socket进行accept操作的场景。也可以在主线程中accpet然后把socket描述符中放入管道传输给工作线程，这种情况工作线程下需要对管道的字节流进行解析分割

**Comment by lingchenye** [comment]
OK
